// Generated by build_questions.py using the PRD dataset plan.
const questions = [
  {
    "id": 1,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a stop sign mean?",
    "options": [
      "Come to a full stop and proceed only when it is safe",
      "Slow down only if another vehicle is close",
      "Yield without stopping",
      "Stop only for pedestrians"
    ],
    "correct": 0,
    "explanation": "A stop sign requires a full stop before you continue when the way is clear.",
    "sourceGroup": 1
  },
  {
    "id": 2,
    "exam": 2,
    "category": "Road Signs",
    "question": "What does a yield sign tell a driver to do?",
    "options": [
      "Come to a full stop every time",
      "Slow down and be prepared to stop if needed",
      "Speed up before entering the intersection",
      "Ignore cross traffic if no cars are visible"
    ],
    "correct": 1,
    "explanation": "A yield sign means reduce speed and give the right-of-way. Stop if traffic conditions require it.",
    "sourceGroup": 2
  },
  {
    "id": 3,
    "exam": 3,
    "category": "Road Signs",
    "question": "What does a school crossing sign mean?",
    "options": [
      "Pedestrians are prohibited",
      "A school crossing is ahead",
      "A playground is closed",
      "Only school buses may enter"
    ],
    "correct": 1,
    "explanation": "This warning sign tells drivers to watch for a school crossing ahead.",
    "sourceGroup": 3
  },
  {
    "id": 4,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a railroad crossing sign warn you about?",
    "options": [
      "A pedestrian tunnel ahead",
      "A blasting zone ahead",
      "A railroad crossing ahead",
      "A truck route ahead"
    ],
    "correct": 2,
    "explanation": "The sign warns that train tracks cross the roadway ahead.",
    "sourceGroup": 4
  },
  {
    "id": 5,
    "exam": 2,
    "category": "Road Signs",
    "question": "What does a traffic signal ahead sign mean?",
    "options": [
      "There is a traffic signal ahead",
      "You must stop immediately",
      "A speed camera is ahead",
      "Only turning traffic is allowed ahead"
    ],
    "correct": 0,
    "explanation": "This warning sign alerts you that a traffic signal is ahead.",
    "sourceGroup": 5
  },
  {
    "id": 6,
    "exam": 3,
    "category": "Road Signs",
    "question": "What does a no left turn sign mean?",
    "options": [
      "Left turns are permitted only after stopping",
      "Left turns are not allowed",
      "U-turns only are prohibited",
      "Traffic must keep left"
    ],
    "correct": 1,
    "explanation": "A no left turn sign means you may not make a left turn at that location.",
    "sourceGroup": 6
  },
  {
    "id": 7,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a no U-turn sign mean?",
    "options": [
      "Left turns are prohibited",
      "No stopping is allowed",
      "U-turns are prohibited",
      "A detour begins ahead"
    ],
    "correct": 2,
    "explanation": "This sign specifically prohibits U-turns.",
    "sourceGroup": 7
  },
  {
    "id": 8,
    "exam": 2,
    "category": "Road Signs",
    "question": "What does a keep right sign mean?",
    "options": [
      "The road becomes one-way",
      "Two-way traffic begins",
      "Drivers must keep to the right",
      "The divided highway ends"
    ],
    "correct": 2,
    "explanation": "Keep right signs direct traffic to pass an obstruction or median on the right side.",
    "sourceGroup": 8
  },
  {
    "id": 9,
    "exam": 3,
    "category": "Road Signs",
    "question": "What does a right lane ends, keep left sign mean?",
    "options": [
      "Merging traffic enters from the left",
      "The right lane ends, so stay left",
      "A divided highway begins",
      "Right turns are required"
    ],
    "correct": 1,
    "explanation": "This sign warns that the right lane ends and drivers should move left when safe.",
    "sourceGroup": 9
  },
  {
    "id": 10,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a divided highway ends sign mean?",
    "options": [
      "The roadway ahead is one way only",
      "Four lanes begin ahead",
      "A divided highway is ending",
      "Two lanes merge into one"
    ],
    "correct": 2,
    "explanation": "It warns that the median or divider separating traffic is ending.",
    "sourceGroup": 10
  },
  {
    "id": 11,
    "exam": 2,
    "category": "Road Signs",
    "question": "What does a two-way traffic sign mean?",
    "options": [
      "A divided highway begins",
      "Two-way traffic is ahead",
      "An intersection is ahead",
      "Four lanes of one-way traffic begin"
    ],
    "correct": 1,
    "explanation": "This sign warns that traffic in both directions will share the road ahead.",
    "sourceGroup": 11
  },
  {
    "id": 12,
    "exam": 3,
    "category": "Road Signs",
    "question": "What does a do not enter sign prevent?",
    "options": [
      "Entrance into a work zone only",
      "Entrance to a dead-end street only",
      "Wrong-way entrance onto one-way roads or ramps",
      "Entrance to a private driveway"
    ],
    "correct": 2,
    "explanation": "Do not enter signs keep drivers from entering against the proper direction of traffic.",
    "sourceGroup": 12
  },
  {
    "id": 13,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a hospital sign with an arrow to the right mean?",
    "options": [
      "A hotel is ahead on the right",
      "A hospital is ahead on the right",
      "A highway curves right",
      "A trail begins on the right"
    ],
    "correct": 1,
    "explanation": "It identifies hospital services in the direction shown by the arrow.",
    "sourceGroup": 13
  },
  {
    "id": 14,
    "exam": 2,
    "category": "Road Signs",
    "question": "What does a hill ahead sign warn about?",
    "options": [
      "A truck stop ahead",
      "A steep hill ahead",
      "No trucks are allowed",
      "An emergency ramp ahead"
    ],
    "correct": 1,
    "explanation": "The sign warns drivers about an upcoming hill grade.",
    "sourceGroup": 14
  },
  {
    "id": 15,
    "exam": 3,
    "category": "Road Signs",
    "question": "What does a slippery when wet sign mean?",
    "options": [
      "The road may be slippery when wet",
      "You are approaching a bridge",
      "Do not drive after drinking",
      "Chains are required ahead"
    ],
    "correct": 0,
    "explanation": "It warns that pavement traction is reduced when the road is wet.",
    "sourceGroup": 15
  },
  {
    "id": 16,
    "exam": 1,
    "category": "Road Signs",
    "question": "What does a merging traffic from the right sign mean?",
    "options": [
      "Traffic must turn right ahead",
      "Traffic will merge in from the right",
      "The right lane is closed permanently",
      "Only right turns are allowed"
    ],
    "correct": 1,
    "explanation": "This sign warns that vehicles will be entering your lane from the right.",
    "sourceGroup": 16
  },
  {
    "id": 17,
    "exam": 2,
    "category": "Road Signs",
    "question": "A rectangular sign is usually what kind of sign?",
    "options": [
      "A speed limit or other regulation sign",
      "A railroad crossing warning sign",
      "A stop sign",
      "A hazard marker only for construction"
    ],
    "correct": 0,
    "explanation": "Regulation signs are normally rectangular, including speed limit signs.",
    "sourceGroup": 17
  },
  {
    "id": 18,
    "exam": 3,
    "category": "Road Signs",
    "question": "A diamond-shaped sign is usually what type of sign?",
    "options": [
      "A destination sign",
      "A road hazard or warning sign",
      "A service sign",
      "A school bus sign only"
    ],
    "correct": 1,
    "explanation": "Warning signs are normally diamond-shaped.",
    "sourceGroup": 18
  },
  {
    "id": 19,
    "exam": 1,
    "category": "Road Signs",
    "question": "What colors are used on signs that tell you the distance to the next highway exit?",
    "options": [
      "Red with white letters",
      "Yellow with black letters",
      "Green with white letters",
      "Black with white letters"
    ],
    "correct": 2,
    "explanation": "Destination signs, including exit information signs, are green with white lettering.",
    "sourceGroup": 19
  },
  {
    "id": 20,
    "exam": 2,
    "category": "Road Signs",
    "question": "What colors are used on most warning signs that show hazards ahead?",
    "options": [
      "Black letters or symbols on yellow",
      "White letters on blue",
      "White letters on green",
      "Black letters on white"
    ],
    "correct": 0,
    "explanation": "Warning signs are usually yellow with black letters or symbols.",
    "sourceGroup": 20
  },
  {
    "id": 21,
    "exam": 3,
    "category": "Road Signs",
    "question": "What colors are used on a typical work zone sign?",
    "options": [
      "White with red letters",
      "Blue with white letters",
      "Orange with black letters",
      "Green with white letters"
    ],
    "correct": 2,
    "explanation": "Work zone warning signs are orange with black lettering or symbols.",
    "sourceGroup": 21
  },
  {
    "id": 22,
    "exam": 1,
    "category": "Road Signs",
    "question": "What colors are used on most service signs?",
    "options": [
      "Blue with white letters",
      "Yellow with black letters",
      "Green with white letters",
      "Red with white letters"
    ],
    "correct": 0,
    "explanation": "Service signs, such as hospital or gas information signs, are blue with white letters.",
    "sourceGroup": 22
  },
  {
    "id": 23,
    "exam": 2,
    "category": "Traffic Control",
    "question": "You come to an intersection with a flashing red light. What should you do?",
    "options": [
      "Slow down and proceed if the road looks clear",
      "Come to a full stop, then go when safe",
      "Stop only if another vehicle is already in the intersection",
      "Treat it like a green light"
    ],
    "correct": 1,
    "explanation": "A flashing red light is treated like a stop sign.",
    "sourceGroup": 23
  },
  {
    "id": 24,
    "exam": 3,
    "category": "Traffic Control",
    "question": "What does a flashing yellow light mean?",
    "options": [
      "Come to a full stop",
      "Proceed with caution",
      "Yield only to pedestrians",
      "Emergency vehicles only"
    ],
    "correct": 1,
    "explanation": "A flashing yellow light warns you to slow down and proceed carefully.",
    "sourceGroup": 24
  },
  {
    "id": 25,
    "exam": 1,
    "category": "Traffic Control",
    "question": "What does a traffic light showing a green arrow and a red light mean?",
    "options": [
      "You may only drive in the direction of the green arrow",
      "You must wait for a full green light",
      "You may go straight only",
      "All traffic must stop"
    ],
    "correct": 0,
    "explanation": "The green arrow permits movement only in the arrow's direction despite the red light for other movements.",
    "sourceGroup": 25
  },
  {
    "id": 26,
    "exam": 2,
    "category": "Traffic Control",
    "question": "Which must you obey over a stop sign, flashing red light, or steady red light?",
    "options": [
      "A police officer",
      "A stop sign",
      "A flashing red light",
      "A steady red light"
    ],
    "correct": 0,
    "explanation": "Directions from a police officer take priority over signs and signals.",
    "sourceGroup": 26
  },
  {
    "id": 27,
    "exam": 3,
    "category": "Traffic Control",
    "question": "If an intersection has a stop sign and a crosswalk but no stop line, where must you stop?",
    "options": [
      "With your front wheels in the crosswalk",
      "At the center of the intersection",
      "Before the crosswalk",
      "Fifty feet before the intersection"
    ],
    "correct": 2,
    "explanation": "Without a stop line, you must stop before entering the crosswalk.",
    "sourceGroup": 27
  },
  {
    "id": 28,
    "exam": 1,
    "category": "Traffic Control",
    "question": "When may you cross a single broken white or yellow line?",
    "options": [
      "Only when doing so will not interfere with traffic",
      "Only at an intersection",
      "Never",
      "Only to pass on a curve"
    ],
    "correct": 0,
    "explanation": "A broken line may be crossed when it is safe and legal to do so.",
    "sourceGroup": 28
  },
  {
    "id": 29,
    "exam": 2,
    "category": "Traffic Control",
    "question": "When may you cross a single solid white line on the highway?",
    "options": [
      "Whenever you want to change lanes",
      "Only to make a U-turn",
      "If traffic conditions require it",
      "Never under any circumstances"
    ],
    "correct": 2,
    "explanation": "Single solid white lines discourage lane changes, but the line may be crossed when traffic conditions require it.",
    "sourceGroup": 29
  },
  {
    "id": 30,
    "exam": 3,
    "category": "Traffic Control",
    "question": "If the road has a solid yellow line and a broken yellow line on your side, when may you pass?",
    "options": [
      "Only at an intersection",
      "Only in an emergency",
      "If traffic is clear",
      "Never"
    ],
    "correct": 2,
    "explanation": "A broken yellow line on your side means passing is allowed if the way is clear.",
    "sourceGroup": 30
  },
  {
    "id": 31,
    "exam": 1,
    "category": "Traffic Control",
    "question": "When may you cross a double solid yellow line?",
    "options": [
      "To pass a slow vehicle",
      "To turn into a driveway",
      "Whenever there is no oncoming traffic",
      "Only during daylight hours"
    ],
    "correct": 1,
    "explanation": "Double solid yellow lines cannot be crossed to pass, but you may cross them to enter a driveway.",
    "sourceGroup": 31
  },
  {
    "id": 32,
    "exam": 2,
    "category": "Traffic Control",
    "question": "A solid white line on the right edge of the roadway slants toward the left. What does that show?",
    "options": [
      "An intersection is just ahead",
      "You must turn left soon",
      "The road will get narrower",
      "A construction detour begins"
    ],
    "correct": 2,
    "explanation": "That pavement marking shows the roadway is narrowing.",
    "sourceGroup": 32
  },
  {
    "id": 33,
    "exam": 3,
    "category": "Traffic Control",
    "question": "What is used on some roads to direct drivers into the correct turning lanes?",
    "options": [
      "Flashing yellow lights",
      "White arrows painted in the lanes",
      "Red edge lines",
      "Reflective posts only"
    ],
    "correct": 1,
    "explanation": "Lane-use arrows painted on the roadway show which turns or movements are allowed from each lane.",
    "sourceGroup": 33
  },
  {
    "id": 34,
    "exam": 1,
    "category": "Traffic Control",
    "question": "As you near an intersection, the light changes from green to yellow. What is your best action?",
    "options": [
      "Speed up to beat the red light",
      "Prepare to stop before the intersection",
      "Stop in the middle of the intersection",
      "Drive through without checking traffic"
    ],
    "correct": 1,
    "explanation": "A steady yellow means the signal is about to turn red, so you should prepare to stop safely.",
    "sourceGroup": 34
  },
  {
    "id": 35,
    "exam": 2,
    "category": "Intersections and Turns",
    "question": "When you want to make a right turn, where should your vehicle be before the turn?",
    "options": [
      "Near the center of the street",
      "Close to the right side of the street",
      "Close to the left side of the street",
      "Past the center of the intersection"
    ],
    "correct": 1,
    "explanation": "For a right turn, position the vehicle near the right curb or right edge of the roadway.",
    "sourceGroup": 35
  },
  {
    "id": 36,
    "exam": 3,
    "category": "Intersections and Turns",
    "question": "You are waiting in an intersection to complete a left turn. How should you keep your wheels?",
    "options": [
      "Turned left",
      "Turned right",
      "Straight",
      "Pointed toward the curb"
    ],
    "correct": 2,
    "explanation": "Keeping your wheels straight helps prevent being pushed into oncoming traffic if you are hit from behind.",
    "sourceGroup": 36
  },
  {
    "id": 37,
    "exam": 1,
    "category": "Intersections and Turns",
    "question": "You come to an intersection that is blocked by traffic. What should you do?",
    "options": [
      "Enter slowly and wait inside the intersection",
      "Stay out of the intersection until you can pass through it",
      "Use your horn so traffic moves",
      "Follow the car ahead as closely as possible"
    ],
    "correct": 1,
    "explanation": "Do not enter a blocked intersection. Wait until there is room to clear it completely.",
    "sourceGroup": 37
  },
  {
    "id": 38,
    "exam": 2,
    "category": "Intersections and Turns",
    "question": "You must yield the right-of-way to an approaching vehicle when you are doing what?",
    "options": [
      "Turning left",
      "Already in a traffic circle",
      "Already in the intersection",
      "Going straight through a green light"
    ],
    "correct": 0,
    "explanation": "Drivers turning left must yield to oncoming traffic going straight or turning right.",
    "sourceGroup": 38
  },
  {
    "id": 39,
    "exam": 3,
    "category": "Intersections and Turns",
    "question": "You hear a siren but cannot yet see the emergency vehicle. What should you do?",
    "options": [
      "Keep driving until you can see it",
      "Pull to the curb and look to see if it is on your street",
      "Speed up and turn away from it",
      "Stop in the center lane"
    ],
    "correct": 1,
    "explanation": "Pull to the right and stop so you can locate the emergency vehicle and yield safely.",
    "sourceGroup": 39
  },
  {
    "id": 40,
    "exam": 1,
    "category": "Intersections and Turns",
    "question": "You are making a left turn from a two-way street into a one-way street. Which lane should you enter?",
    "options": [
      "The right lane",
      "The center lane",
      "The left lane",
      "Any lane with the least traffic"
    ],
    "correct": 2,
    "explanation": "A left turn into a one-way street should end in the left lane of that street.",
    "sourceGroup": 40
  },
  {
    "id": 41,
    "exam": 2,
    "category": "Intersections and Turns",
    "question": "When do you have the right-of-way in a traffic circle?",
    "options": [
      "When you are entering it",
      "When you are already in it",
      "Only if you are turning right",
      "Only if you honk first"
    ],
    "correct": 1,
    "explanation": "Vehicles already in the traffic circle have the right-of-way.",
    "sourceGroup": 41
  },
  {
    "id": 42,
    "exam": 3,
    "category": "Intersections and Turns",
    "question": "What must you do when entering a roadway from a private road or driveway?",
    "options": [
      "Merge quickly so traffic does not slow down",
      "Yield the right-of-way to pedestrians and roadway traffic",
      "Stop partly in the roadway so others can see you",
      "Sound your horn and pull out"
    ],
    "correct": 1,
    "explanation": "Drivers entering from private roads must yield to all pedestrians and traffic on the roadway.",
    "sourceGroup": 42
  },
  {
    "id": 43,
    "exam": 1,
    "category": "Intersections and Turns",
    "question": "You want to turn left at a green light, but oncoming traffic is heavy. What should you do?",
    "options": [
      "Take the right-of-way because your light is green",
      "Wait at the crosswalk",
      "Wait in the center of the intersection until traffic clears",
      "Use the shoulder to go around oncoming cars"
    ],
    "correct": 2,
    "explanation": "You may enter the intersection and wait to turn left when the light is green, as long as you yield to oncoming traffic.",
    "sourceGroup": 43
  },
  {
    "id": 44,
    "exam": 2,
    "category": "Intersections and Turns",
    "question": "How far before a turn or lane change does New York law require you to signal?",
    "options": [
      "At least 50 feet",
      "At least 75 feet",
      "At least 100 feet",
      "At least 200 feet"
    ],
    "correct": 2,
    "explanation": "New York requires a signal at least 100 feet before a turn or lane change.",
    "sourceGroup": 44
  },
  {
    "id": 45,
    "exam": 3,
    "category": "Intersections and Turns",
    "question": "When two vehicles enter an intersection from different roads at the same time, which one must yield?",
    "options": [
      "The vehicle on the right",
      "Neither vehicle",
      "The vehicle on the left",
      "The larger vehicle"
    ],
    "correct": 2,
    "explanation": "At the same time, the driver on the left yields to the driver on the right.",
    "sourceGroup": 45
  },
  {
    "id": 46,
    "exam": 1,
    "category": "Intersections and Turns",
    "question": "What should you do when you see an emergency vehicle parked with emergency or hazard lights activated on a highway or parkway?",
    "options": [
      "Maintain your speed and lane",
      "Move out of the lane closest to the vehicle if you can do so safely",
      "Make a U-turn to avoid it",
      "Stop behind it with hazard flashers on"
    ],
    "correct": 1,
    "explanation": "New York's Move Over Law requires drivers to move over when possible or slow down when approaching stopped emergency or hazard vehicles.",
    "sourceGroup": 46
  },
  {
    "id": 47,
    "exam": 2,
    "category": "Intersections and Turns",
    "question": "Which vehicles require you to pull over and stop when they are responding to an emergency?",
    "options": [
      "Vehicles displaying blue, green, or amber lights only",
      "Authorized emergency vehicles",
      "All stopped school buses",
      "Any tow truck"
    ],
    "correct": 1,
    "explanation": "You must yield by pulling over and stopping for authorized emergency vehicles using sirens or lights.",
    "sourceGroup": 47
  },
  {
    "id": 48,
    "exam": 3,
    "category": "Intersections and Turns",
    "question": "What is the name of the law that requires drivers to use care around stopped emergency or hazard vehicles with activated lights?",
    "options": [
      "Right-of-Way Law",
      "Move Over Law",
      "Green Light Law",
      "Brianna's Law"
    ],
    "correct": 1,
    "explanation": "The Move Over Law requires drivers to move over when possible or slow down around stopped emergency and hazard vehicles.",
    "sourceGroup": 48
  },
  {
    "id": 49,
    "exam": 1,
    "category": "Intersections and Turns",
    "question": "A driver approaching an intersection must yield the right-of-way to what traffic?",
    "options": [
      "Traffic that is already in the intersection",
      "Only vehicles on the left",
      "Only vehicles making right turns",
      "Traffic that arrives later"
    ],
    "correct": 0,
    "explanation": "Drivers must yield to vehicles already in the intersection.",
    "sourceGroup": 49
  },
  {
    "id": 50,
    "exam": 2,
    "category": "Passing",
    "question": "After passing another vehicle, when should you return to the right lane?",
    "options": [
      "As soon as your turn signal is on",
      "When you can see the front bumper of the other vehicle in your mirror",
      "When the other driver flashes headlights",
      "Immediately after moving ahead of its hood"
    ],
    "correct": 1,
    "explanation": "Wait until you can see the front bumper of the passed vehicle in your mirror before moving back right.",
    "sourceGroup": 50
  },
  {
    "id": 51,
    "exam": 3,
    "category": "Passing",
    "question": "In which situation is passing always forbidden?",
    "options": [
      "When the vehicle ahead is turning left",
      "When the vehicle ahead is stopped for a pedestrian in a crosswalk",
      "On a one-way street with two lanes",
      "When the vehicle ahead is parking at the curb"
    ],
    "correct": 1,
    "explanation": "You may never pass a vehicle that is stopped for a pedestrian in a crosswalk.",
    "sourceGroup": 51
  },
  {
    "id": 52,
    "exam": 1,
    "category": "Passing",
    "question": "When may you pass another vehicle on the right?",
    "options": [
      "When it is waiting to turn left",
      "Whenever you are in a hurry",
      "Only on curves",
      "Only if you honk first"
    ],
    "correct": 0,
    "explanation": "Passing on the right is permitted in limited cases, such as when the other vehicle is waiting to turn left.",
    "sourceGroup": 52
  },
  {
    "id": 53,
    "exam": 2,
    "category": "Passing",
    "question": "On a three-lane expressway, another driver begins passing you on the right. When is that action allowed?",
    "options": [
      "Never",
      "Only if that driver uses a horn",
      "As long as no signs forbid passing on the right",
      "Only if you slow to a stop"
    ],
    "correct": 2,
    "explanation": "Passing on the right can be legal on multi-lane roads if signs do not prohibit it and it is done safely.",
    "sourceGroup": 53
  },
  {
    "id": 54,
    "exam": 3,
    "category": "Passing",
    "question": "What does it mean when a school bus is stopped and its red lights are flashing?",
    "options": [
      "You may pass if no children are in the roadway",
      "You may not pass while the red lights are flashing",
      "You may pass if you are approaching from the front",
      "You may pass if traffic behind you is heavy"
    ],
    "correct": 1,
    "explanation": "Red flashing school bus lights mean traffic must stop and may not pass until the lights stop flashing.",
    "sourceGroup": 54
  },
  {
    "id": 55,
    "exam": 1,
    "category": "Passing",
    "question": "When you want to overtake and pass another vehicle, what should you do first?",
    "options": [
      "Stay close behind it to shorten the pass",
      "Signal and pass only when it is safe",
      "Wait for the other driver to wave you around",
      "Change lanes suddenly so the driver notices you"
    ],
    "correct": 1,
    "explanation": "Check mirrors, signal, and pass only when the road is clear and legal.",
    "sourceGroup": 55
  },
  {
    "id": 56,
    "exam": 2,
    "category": "Passing",
    "question": "In general, on which side should you pass vehicles moving in the same direction?",
    "options": [
      "On the shoulder",
      "On the right",
      "On the left",
      "On either side"
    ],
    "correct": 2,
    "explanation": "The normal rule is to pass on the left.",
    "sourceGroup": 56
  },
  {
    "id": 57,
    "exam": 3,
    "category": "Passing",
    "question": "The vehicle behind you begins to pass. What should you do?",
    "options": [
      "Maintain speed and honk",
      "Slow slightly and stay in your lane",
      "Move left to block the pass",
      "Speed up so traffic keeps moving"
    ],
    "correct": 1,
    "explanation": "Help the passing driver by staying in your lane and slowing slightly if needed.",
    "sourceGroup": 57
  },
  {
    "id": 58,
    "exam": 1,
    "category": "Parking",
    "question": "In a parking space reserved for people with disabilities, a non-disabled driver may do what?",
    "options": [
      "Park only in an emergency",
      "Stop briefly to unload packages",
      "Neither park, stop, nor stand there",
      "Stand there if staying in the vehicle"
    ],
    "correct": 2,
    "explanation": "Reserved disabled spaces may not be used by drivers without the proper permit or plates transporting the eligible person.",
    "sourceGroup": 58
  },
  {
    "id": 59,
    "exam": 2,
    "category": "Parking",
    "question": "Before leaving a parking space parallel to the curb, how should you check for traffic?",
    "options": [
      "Use only the inside mirror",
      "Sound your horn",
      "Turn your head and look for traffic",
      "Use your flashers first"
    ],
    "correct": 2,
    "explanation": "Turning your head helps you check blind spots before pulling out.",
    "sourceGroup": 59
  },
  {
    "id": 60,
    "exam": 3,
    "category": "Parking",
    "question": "What does a no stopping sign mean?",
    "options": [
      "You may stop briefly to discharge passengers",
      "You may stop only to obey traffic, a signal, an officer, or avoid conflict",
      "You may stop for less than five minutes",
      "You may stop to unload packages"
    ],
    "correct": 1,
    "explanation": "A no stopping zone allows stopping only for legal necessity or to avoid danger.",
    "sourceGroup": 60
  },
  {
    "id": 61,
    "exam": 1,
    "category": "Parking",
    "question": "When may a vehicle use disabled parking plates or a disabled parking permit to park in a reserved space?",
    "options": [
      "Any time the driver has the permit in the glove box",
      "Only when the disabled person connected to the permit or registration is being transported",
      "Whenever a family member is disabled",
      "Only on weekdays"
    ],
    "correct": 1,
    "explanation": "Reserved parking is allowed only when the person who qualifies for the permit or plates is being transported.",
    "sourceGroup": 61
  },
  {
    "id": 62,
    "exam": 2,
    "category": "Parking",
    "question": "After parallel parking on a level street between two cars, what should you do with the front wheels?",
    "options": [
      "Leave them turned toward the curb",
      "Straighten them and leave room between cars",
      "Turn them away from the curb",
      "Turn them sharply left"
    ],
    "correct": 1,
    "explanation": "After parking on a level street, straighten the wheels and leave space from the cars ahead and behind.",
    "sourceGroup": 62
  },
  {
    "id": 63,
    "exam": 3,
    "category": "Parking",
    "question": "Where may you never park?",
    "options": [
      "On a one-way street",
      "At the entrance to a building",
      "In a crosswalk",
      "On the right side of the road"
    ],
    "correct": 2,
    "explanation": "Parking in a crosswalk is always illegal.",
    "sourceGroup": 63
  },
  {
    "id": 64,
    "exam": 1,
    "category": "Parking",
    "question": "What does a no parking sign mean?",
    "options": [
      "You may never stop there for any reason",
      "You may stop temporarily to load or unload passengers or merchandise",
      "You may leave the vehicle for less than five minutes",
      "You may park if the driver stays inside"
    ],
    "correct": 1,
    "explanation": "No parking still allows a temporary stop to load or unload passengers or merchandise.",
    "sourceGroup": 64
  },
  {
    "id": 65,
    "exam": 2,
    "category": "Parking",
    "question": "When may you get out of a car on the traffic side if you are parked parallel to the curb?",
    "options": [
      "Only during daylight hours",
      "Only after using four-way flashers",
      "When doing so will not interfere with traffic",
      "Only when the nearest light turns red"
    ],
    "correct": 2,
    "explanation": "You may exit on the traffic side only when it will not interfere with other road users.",
    "sourceGroup": 65
  },
  {
    "id": 66,
    "exam": 3,
    "category": "Parking",
    "question": "What does a no standing sign mean?",
    "options": [
      "You may stop to load or unload merchandise",
      "You may stop only temporarily to pick up or discharge passengers",
      "You may never stop under any circumstances",
      "You may park if you stay in the car"
    ],
    "correct": 1,
    "explanation": "No standing allows a temporary stop only to pick up or drop off passengers.",
    "sourceGroup": 66
  },
  {
    "id": 67,
    "exam": 1,
    "category": "Parking",
    "question": "How close may you park to a fire hydrant in New York?",
    "options": [
      "No closer than 15 feet",
      "No closer than 10 feet",
      "No closer than 20 feet",
      "No closer than 25 feet"
    ],
    "correct": 0,
    "explanation": "State rules prohibit parking within 15 feet of a fire hydrant.",
    "sourceGroup": 67
  },
  {
    "id": 68,
    "exam": 2,
    "category": "Defensive Driving",
    "question": "A safe speed for your vehicle depends mainly on what?",
    "options": [
      "The posted speed limit only",
      "The driver's confidence",
      "The weather and road conditions",
      "How quickly your car accelerates"
    ],
    "correct": 2,
    "explanation": "A safe speed depends on conditions, even when the posted speed limit is higher.",
    "sourceGroup": 68
  },
  {
    "id": 69,
    "exam": 3,
    "category": "Defensive Driving",
    "question": "Which statement is always true about road rage?",
    "options": [
      "There is nothing you can do to prevent it",
      "Only violent people experience it",
      "You should remain polite to aggressive drivers",
      "You should hold your lane at all costs"
    ],
    "correct": 2,
    "explanation": "Staying calm and not escalating a situation is the safest response.",
    "sourceGroup": 69
  },
  {
    "id": 70,
    "exam": 1,
    "category": "Defensive Driving",
    "question": "Seat belts work best when they are worn by whom?",
    "options": [
      "The driver only",
      "Passengers only on expressways",
      "All occupants every time they are in the car",
      "Only people sitting in front"
    ],
    "correct": 2,
    "explanation": "Seat belts protect drivers and passengers best when everyone wears them every trip.",
    "sourceGroup": 70
  },
  {
    "id": 71,
    "exam": 2,
    "category": "Defensive Driving",
    "question": "A lane closed ahead sign warns of a work zone. What should you do?",
    "options": [
      "Merge into the correct lane when it is safe",
      "Drive to the end of the closed lane before looking",
      "Speed up and force your way in",
      "Ignore the sign until you see workers"
    ],
    "correct": 0,
    "explanation": "Merge safely when warned that a lane is closing rather than waiting until the last second.",
    "sourceGroup": 71
  },
  {
    "id": 72,
    "exam": 3,
    "category": "Defensive Driving",
    "question": "What are minimum speed signs designed to do?",
    "options": [
      "Show road conditions",
      "Keep traffic flowing smoothly",
      "Protect only pedestrians",
      "Test future traffic signal needs"
    ],
    "correct": 1,
    "explanation": "Minimum speed signs help maintain safe traffic flow by discouraging very slow travel.",
    "sourceGroup": 72
  },
  {
    "id": 73,
    "exam": 1,
    "category": "Defensive Driving",
    "question": "Driving in a state of rage can do what?",
    "options": [
      "Affect your judgment, raise crash risk, and lead to license consequences",
      "Improve alertness",
      "Help you respond more quickly",
      "Reduce the chance of a collision"
    ],
    "correct": 0,
    "explanation": "Road rage harms judgment, increases crash risk, and can result in legal penalties.",
    "sourceGroup": 73
  },
  {
    "id": 74,
    "exam": 2,
    "category": "Defensive Driving",
    "question": "One rule of defensive driving is to do what with your eyes?",
    "options": [
      "Focus only on the vehicle ahead",
      "Stay alert and keep your eyes moving",
      "Look straight ahead only",
      "Check mirrors only when turning"
    ],
    "correct": 1,
    "explanation": "Scanning ahead, to the sides, and in mirrors helps you spot problems early.",
    "sourceGroup": 74
  },
  {
    "id": 75,
    "exam": 3,
    "category": "Defensive Driving",
    "question": "On long trips, what helps prevent drowsiness?",
    "options": [
      "Driving faster",
      "Turning the radio up",
      "Stopping at regular intervals for rest",
      "Opening a window instead of resting"
    ],
    "correct": 2,
    "explanation": "Regular breaks are an effective way to reduce fatigue on long drives.",
    "sourceGroup": 75
  },
  {
    "id": 76,
    "exam": 1,
    "category": "Defensive Driving",
    "question": "On a New York highway with no posted speed limit, what is the fastest legal speed?",
    "options": [
      "50 mph",
      "55 mph",
      "60 mph",
      "65 mph"
    ],
    "correct": 1,
    "explanation": "When no lower speed is posted, the general maximum speed is 55 mph.",
    "sourceGroup": 76
  },
  {
    "id": 77,
    "exam": 2,
    "category": "Defensive Driving",
    "question": "What is true of work zones?",
    "options": [
      "They are dangerous only at night",
      "Rear-end collisions are the most common crash there",
      "They are always stationary and easy to avoid",
      "Speeding fines never change there"
    ],
    "correct": 1,
    "explanation": "Rear-end crashes are common in work zones because traffic often slows or stops unexpectedly.",
    "sourceGroup": 77
  },
  {
    "id": 78,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "Drivers under the influence of alcohol are whose problem?",
    "options": [
      "Only the drinker's problem",
      "Only a police enforcement problem",
      "Every driver's problem",
      "Not a major issue in New York"
    ],
    "correct": 2,
    "explanation": "Impaired driving puts everyone on the road at risk.",
    "sourceGroup": 78
  },
  {
    "id": 79,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "What can happen when alcohol and another drug are combined in your blood?",
    "options": [
      "The effects of both may increase",
      "The alcohol is canceled out",
      "Driving ability is unchanged",
      "The drug becomes harmless"
    ],
    "correct": 0,
    "explanation": "Alcohol and other drugs can intensify each other's effects and make driving more dangerous.",
    "sourceGroup": 79
  },
  {
    "id": 80,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "What effect can drinking alcohol while taking prescription or over-the-counter medicine have?",
    "options": [
      "It can multiply the effects of the alcohol",
      "It always makes you more alert",
      "It reduces the effect of the medicine only",
      "It has no effect because they are different substances"
    ],
    "correct": 0,
    "explanation": "Alcohol can interact with medicines and worsen impairment.",
    "sourceGroup": 80
  },
  {
    "id": 81,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "Which factors influence the effects of alcohol on a person?",
    "options": [
      "The amount of food in the stomach, body weight, and time between drinks",
      "Only the type of alcohol consumed",
      "Only how physically fit the person is",
      "Only the weather"
    ],
    "correct": 0,
    "explanation": "Food, body weight, and the time between drinks all affect BAC and impairment.",
    "sourceGroup": 81
  },
  {
    "id": 82,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "Blood alcohol content does not depend on which of the following?",
    "options": [
      "Your body weight",
      "How much you drink",
      "How much time passes between drinks",
      "How physically fit you are"
    ],
    "correct": 3,
    "explanation": "Physical fitness does not lower BAC.",
    "sourceGroup": 82
  },
  {
    "id": 83,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "What is the only effective way to reduce your BAC?",
    "options": [
      "Exercise",
      "Drink coffee",
      "Take a cold shower",
      "Allow time for your body to remove the alcohol"
    ],
    "correct": 3,
    "explanation": "Only time lowers BAC. Coffee, showers, and exercise do not make you sober.",
    "sourceGroup": 83
  },
  {
    "id": 84,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "Which of these does not happen after drinking alcohol?",
    "options": [
      "Reaction time slows",
      "Judgment of distance is distorted",
      "You become calmer so you can concentrate better",
      "You are less alert"
    ],
    "correct": 2,
    "explanation": "Alcohol does not improve concentration. It impairs judgment and alertness.",
    "sourceGroup": 84
  },
  {
    "id": 85,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "If you drink socially, what is the best way to help ensure safe driving?",
    "options": [
      "Take a cold shower before driving",
      "Ride home with a sober friend",
      "Stop drinking 30 minutes before leaving",
      "Drink coffee before driving"
    ],
    "correct": 1,
    "explanation": "The safest choice is not to drive after drinking and instead ride with someone sober.",
    "sourceGroup": 85
  },
  {
    "id": 86,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "What should a driver do before driving after taking a non-prescription drug?",
    "options": [
      "Read the label",
      "Drive only in daylight",
      "Drink coffee first",
      "Assume it is safe because it was bought without a prescription"
    ],
    "correct": 0,
    "explanation": "Many over-the-counter medicines can impair driving, so always check the label.",
    "sourceGroup": 86
  },
  {
    "id": 87,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "What happens to your driver license if you refuse a chemical test after arrest?",
    "options": [
      "Nothing happens unless you are convicted later",
      "You cannot be arrested",
      "Your license can be taken away",
      "You automatically win the case"
    ],
    "correct": 2,
    "explanation": "Under implied consent rules, refusing a chemical test can cause suspension or revocation.",
    "sourceGroup": 87
  },
  {
    "id": 88,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "Drinking alcohol and driving is what kind of traffic safety problem?",
    "options": [
      "A minor problem",
      "A serious problem",
      "Safe if only a few drinks were consumed",
      "Dangerous only to the drinking driver"
    ],
    "correct": 1,
    "explanation": "Alcohol-impaired driving is a major and serious traffic safety problem.",
    "sourceGroup": 88
  },
  {
    "id": 89,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "What effect does coffee have on BAC after drinking alcohol?",
    "options": [
      "It lowers BAC",
      "It cancels the alcohol",
      "It has no effect on BAC",
      "It increases BAC"
    ],
    "correct": 2,
    "explanation": "Coffee may make you feel more awake, but it does not reduce BAC.",
    "sourceGroup": 89
  },
  {
    "id": 90,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "Which driving-related abilities does alcohol affect?",
    "options": [
      "Only reaction time",
      "Only judgment of distances",
      "Only recovery from headlight glare",
      "All of these abilities"
    ],
    "correct": 3,
    "explanation": "Alcohol affects glare recovery, reaction time, and distance judgment.",
    "sourceGroup": 90
  },
  {
    "id": 91,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "In New York, what BAC is evidence of intoxication?",
    "options": [
      "0.03%",
      "0.05%",
      "0.08%",
      "0.10%"
    ],
    "correct": 2,
    "explanation": "A BAC of 0.08% or higher is evidence of intoxication for DWI.",
    "sourceGroup": 91
  },
  {
    "id": 92,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "Which kinds of drugs other than alcohol can affect driving ability?",
    "options": [
      "Only illegal drugs",
      "Allergy medicine, marijuana, and cold remedies",
      "Only prescription sleeping pills",
      "Only pain medicine"
    ],
    "correct": 1,
    "explanation": "Many legal and illegal drugs can impair driving, including cold remedies, allergy medicine, and marijuana.",
    "sourceGroup": 92
  },
  {
    "id": 93,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "Which statement about BAC is true?",
    "options": [
      "Physical fitness lowers BAC quickly",
      "A breath test is one way to measure BAC",
      "Coffee or a cold shower lowers BAC",
      "A chemical test is always required for a conviction"
    ],
    "correct": 1,
    "explanation": "Breath, blood, urine, or saliva tests can measure BAC.",
    "sourceGroup": 93
  },
  {
    "id": 94,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "On average, how long does it take the human body to dispose of the alcohol in about 12 ounces of beer?",
    "options": [
      "About one hour",
      "About five minutes",
      "About five hours",
      "About one day"
    ],
    "correct": 0,
    "explanation": "On average, the body removes about the alcohol in one 12-ounce beer in about an hour.",
    "sourceGroup": 94
  },
  {
    "id": 95,
    "exam": 2,
    "category": "Alcohol and Drugs",
    "question": "A chemical test is used to measure what?",
    "options": [
      "Reaction time",
      "Driving skill",
      "Blood alcohol content",
      "Eyesight"
    ],
    "correct": 2,
    "explanation": "Chemical tests measure the amount of alcohol in your body, usually reported as BAC.",
    "sourceGroup": 95
  },
  {
    "id": 96,
    "exam": 3,
    "category": "Alcohol and Drugs",
    "question": "What can result from driving under the influence of alcohol or other drugs?",
    "options": [
      "Possible jail time, fines, and driver license revocation",
      "Only a warning on the first offense",
      "Only higher insurance rates",
      "No consequences if no crash occurs"
    ],
    "correct": 0,
    "explanation": "Alcohol- and drug-related driving offenses can lead to fines, jail, and loss of license.",
    "sourceGroup": 96
  },
  {
    "id": 97,
    "exam": 1,
    "category": "Alcohol and Drugs",
    "question": "What does alcohol do to driving skills and judgment?",
    "options": [
      "It helps both",
      "It harms both",
      "It harms judgment only",
      "It harms driving skill only"
    ],
    "correct": 1,
    "explanation": "Alcohol impairs both the physical and mental abilities needed for safe driving.",
    "sourceGroup": 97
  },
  {
    "id": 98,
    "exam": 2,
    "category": "Special Driving Conditions",
    "question": "You are entering a highway with a very short entrance lane. What is the safest way to enter traffic?",
    "options": [
      "Use as much of the ramp as possible to reach cruising speed",
      "Stop at the end of the ramp and wait for a gap",
      "Drive onto the shoulder until you can merge",
      "Use the left lane of the highway to gain speed"
    ],
    "correct": 0,
    "explanation": "Use the acceleration lane or ramp to get close to highway speed before merging.",
    "sourceGroup": 98
  },
  {
    "id": 99,
    "exam": 3,
    "category": "Special Driving Conditions",
    "question": "When attempting to stop on a slippery road, what is the best action?",
    "options": [
      "Apply the brakes quickly and firmly",
      "Shift into neutral and coast",
      "Apply the brakes in slow, steady strokes",
      "Turn the wheel sharply to the shoulder"
    ],
    "correct": 2,
    "explanation": "Gentle, steady braking helps maintain traction on slippery surfaces.",
    "sourceGroup": 99
  },
  {
    "id": 100,
    "exam": 1,
    "category": "Special Driving Conditions",
    "question": "You have just left an expressway and are beginning to drive on an ordinary highway. What should you do?",
    "options": [
      "Check your speedometer to keep at the lower speed limit",
      "Stay at expressway speed until traffic forces you to slow",
      "Check tire pressure immediately",
      "Double your following distance regardless of traffic"
    ],
    "correct": 0,
    "explanation": "Drivers often continue too fast after leaving an expressway, so check your speed.",
    "sourceGroup": 100
  },
  {
    "id": 101,
    "exam": 2,
    "category": "Special Driving Conditions",
    "question": "What should you do at a railroad crossing that has no signals or gates?",
    "options": [
      "Always stop completely",
      "Slow down and be prepared to stop",
      "Increase speed to cross quickly",
      "Assume no train is coming"
    ],
    "correct": 1,
    "explanation": "You should slow down, look, listen, and be ready to stop for a train.",
    "sourceGroup": 101
  },
  {
    "id": 102,
    "exam": 3,
    "category": "Special Driving Conditions",
    "question": "If traffic prevents you from crossing all the way over railroad tracks, when may you proceed?",
    "options": [
      "When at least half of your vehicle can clear the tracks",
      "When no train is visible",
      "Only when there is room for your vehicle on the other side",
      "When the driver behind you honks"
    ],
    "correct": 2,
    "explanation": "Never enter a railroad crossing unless you can clear the tracks completely.",
    "sourceGroup": 102
  },
  {
    "id": 103,
    "exam": 1,
    "category": "Special Driving Conditions",
    "question": "When driving in heavy fog during daylight, which headlights should you use?",
    "options": [
      "No headlights",
      "Parking lights only",
      "High beams",
      "Low beams"
    ],
    "correct": 3,
    "explanation": "Low beams reduce glare reflected by fog better than high beams.",
    "sourceGroup": 103
  },
  {
    "id": 104,
    "exam": 2,
    "category": "Special Driving Conditions",
    "question": "Your car begins to skid on a slippery road. Which way should you steer?",
    "options": [
      "Toward the side of the road",
      "In the direction you want the front wheels to go",
      "The opposite way from the skid",
      "Back and forth quickly"
    ],
    "correct": 1,
    "explanation": "Steering in the direction you want the front wheels to travel helps regain control.",
    "sourceGroup": 104
  },
  {
    "id": 105,
    "exam": 3,
    "category": "Special Driving Conditions",
    "question": "Why is expressway driving different from driving on an ordinary street?",
    "options": [
      "Trucks always travel slower there",
      "You must think faster and handle your vehicle more effectively",
      "There are no blind spots on expressways",
      "There is less need to plan ahead"
    ],
    "correct": 1,
    "explanation": "Higher speeds leave less time to react, so expressway driving requires quicker judgment and control.",
    "sourceGroup": 105
  },
  {
    "id": 106,
    "exam": 1,
    "category": "Special Driving Conditions",
    "question": "Why do expressways have acceleration lanes?",
    "options": [
      "To test your brakes",
      "To stop and wait for an opening",
      "To reach proper speed before blending with traffic",
      "To pass vehicles on the right"
    ],
    "correct": 2,
    "explanation": "Acceleration lanes let drivers speed up and merge more safely.",
    "sourceGroup": 106
  },
  {
    "id": 107,
    "exam": 2,
    "category": "Special Driving Conditions",
    "question": "If a tire blows out while you are driving, what should you do first?",
    "options": [
      "Brake hard immediately",
      "Hold the steering wheel firmly and ease off the gas",
      "Shift into neutral and stop in your lane",
      "Turn sharply toward the shoulder"
    ],
    "correct": 1,
    "explanation": "A blowout should be handled by maintaining control and letting the vehicle slow gradually.",
    "sourceGroup": 107
  },
  {
    "id": 108,
    "exam": 3,
    "category": "Special Driving Conditions",
    "question": "May you ever drive around or under a railroad crossing gate that is being lowered or raised?",
    "options": [
      "Yes, if no train is close",
      "Yes, if the gate is high enough",
      "Only if traffic is heavy",
      "No, under no circumstances"
    ],
    "correct": 3,
    "explanation": "Driving around or under crossing gates is never allowed.",
    "sourceGroup": 108
  },
  {
    "id": 109,
    "exam": 1,
    "category": "Special Driving Conditions",
    "question": "If your brake pedal suddenly sinks to the floor, what should you try first?",
    "options": [
      "Pump the pedal to build pressure",
      "Turn off the engine",
      "Hook your toe under the pedal",
      "Use the parking brake hard right away"
    ],
    "correct": 0,
    "explanation": "Pumping the brake pedal may restore enough pressure to slow or stop the vehicle.",
    "sourceGroup": 109
  },
  {
    "id": 110,
    "exam": 2,
    "category": "Special Driving Conditions",
    "question": "Your right wheels run onto a soft shoulder. What is the best way to get back on the highway?",
    "options": [
      "Brake hard and steer sharply left",
      "Ease off the gas and brake gently",
      "Turn left hard, then right hard",
      "Stop completely on the shoulder first"
    ],
    "correct": 1,
    "explanation": "Slow down gently and return to the pavement carefully to avoid a skid.",
    "sourceGroup": 110
  },
  {
    "id": 111,
    "exam": 3,
    "category": "Sharing the Road",
    "question": "On a roadway, where must a bicyclist generally ride?",
    "options": [
      "On the right side of the road",
      "Facing traffic on the left side",
      "On either side of the road",
      "Where there is the least traffic"
    ],
    "correct": 0,
    "explanation": "Bicyclists generally ride on the right side and follow the same traffic direction as motor vehicles.",
    "sourceGroup": 111
  },
  {
    "id": 112,
    "exam": 1,
    "category": "Sharing the Road",
    "question": "If there are no sidewalks, on which side of the road should a pedestrian walk?",
    "options": [
      "The same side as traffic",
      "The side facing oncoming traffic",
      "The side with lighter traffic",
      "Either side"
    ],
    "correct": 1,
    "explanation": "Pedestrians should walk facing traffic when no sidewalk is available.",
    "sourceGroup": 112
  },
  {
    "id": 113,
    "exam": 2,
    "category": "Sharing the Road",
    "question": "What should a motorist do when approaching a bicyclist?",
    "options": [
      "Proceed as usual",
      "Pass as quickly as possible",
      "Exercise extreme caution",
      "Swerve into the opposite lane immediately"
    ],
    "correct": 2,
    "explanation": "Drivers should give bicyclists extra space and use great care.",
    "sourceGroup": 113
  },
  {
    "id": 114,
    "exam": 3,
    "category": "Sharing the Road",
    "question": "What does a slow-moving vehicle emblem look like?",
    "options": [
      "A square red sign",
      "A round green sign",
      "A triangular orange sign",
      "A yellow diamond sign"
    ],
    "correct": 2,
    "explanation": "The slow-moving vehicle emblem is a fluorescent orange triangle.",
    "sourceGroup": 114
  },
  {
    "id": 115,
    "exam": 1,
    "category": "Sharing the Road",
    "question": "How does a bicyclist differ from a motorist under New York rules?",
    "options": [
      "A bicyclist does not need to obey traffic laws",
      "A bicyclist does not have to signal turns",
      "A bicyclist is not required to insure the bicycle",
      "A bicyclist never has to report crashes"
    ],
    "correct": 2,
    "explanation": "Bicyclists must follow traffic laws, but bicycle insurance is not required like motor vehicle insurance.",
    "sourceGroup": 115
  },
  {
    "id": 116,
    "exam": 2,
    "category": "Sharing the Road",
    "question": "When does a blind pedestrian have the legal right-of-way while crossing the street?",
    "options": [
      "Only when wearing dark glasses",
      "Only when helped by another person",
      "When using a guide dog or a white or metallic cane",
      "Only at a traffic signal"
    ],
    "correct": 2,
    "explanation": "Blind pedestrians using a guide dog or white/metallic cane must always be given the right-of-way.",
    "sourceGroup": 116
  },
  {
    "id": 117,
    "exam": 3,
    "category": "Sharing the Road",
    "question": "Where must drivers yield to pedestrians?",
    "options": [
      "Only at marked crosswalks",
      "At all crosswalks and intersections",
      "Only when a crossing guard is present",
      "Only on school days"
    ],
    "correct": 1,
    "explanation": "Drivers must yield to pedestrians at both marked and unmarked crosswalks and intersections.",
    "sourceGroup": 117
  },
  {
    "id": 118,
    "exam": 1,
    "category": "Sharing the Road",
    "question": "What should you do if another vehicle is stopped for pedestrians at a crosswalk?",
    "options": [
      "Pass it carefully on the right",
      "Pass it only if the horn is used",
      "Never pass it",
      "Pass it if you cannot see pedestrians"
    ],
    "correct": 2,
    "explanation": "Do not pass a vehicle stopped at a crosswalk because pedestrians may be crossing where you cannot see them.",
    "sourceGroup": 118
  },
  {
    "id": 119,
    "exam": 2,
    "category": "Sharing the Road",
    "question": "Near which places should drivers be especially alert for children?",
    "options": [
      "Only near shopping centers",
      "Near schools, bus stops, parks, playgrounds, and ice cream trucks",
      "Only near highways",
      "Only in rural areas"
    ],
    "correct": 1,
    "explanation": "Children can enter the roadway unexpectedly near places where they gather.",
    "sourceGroup": 119
  },
  {
    "id": 120,
    "exam": 3,
    "category": "Sharing the Road",
    "question": "When backing up near children, what should you rely on most?",
    "options": [
      "Your mirrors only",
      "Your horn",
      "Looking through the back window and checking behind the vehicle",
      "The backup camera only"
    ],
    "correct": 2,
    "explanation": "Mirrors and cameras help, but drivers still need to look directly behind the vehicle.",
    "sourceGroup": 120
  }
];

window.questions = questions;
